version: '3'

services:
  app:
    build:
      context: ./containers/app
    working_dir: /java_app_sample
    volumes:
      - ./:/java_app_sample
      - ./build/libs/:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"

  db:
    build:
      context: ./containers/db
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/mysql
    ports:
      - "3306:3306"

volumes:
  mysql: {}
